### PR TITLE
[refactor] `MachineSteps` should not be defined in `Options`

### PR DESCRIPTION
**Pull request by JacquesCarette**
Remove the definition of `MachineSteps` from `Options` and put it in `Machine.Steps` instead.

### CODE REVIEW

**Comment by gallais** [comment]
We should probably take this opportunity to also refactor:

https://github.com/msp-strath/TypOS/blob/3ca77a0069904aabd715a462d12222fe4c8aeacf/Src/Options.hs#L55-L67

It makes little sense that we're using `[minBound..maxBound]` for error generation but then
manually defined `readSteps` instead of doing `lookup` on the rendered step names.

**Comment by JacquesCarette** [comment]
Indeed. And some of those functions should be moved as well. Will do.

**Comment by JacquesCarette** [comment]
Latest commit should be more along the lines you were talking about?

**Comment by JacquesCarette** [comment]
Thanks for the cleanup - I knew there was a more robust approach, it just escaped me earlier.

**Pull request merged**
